#!/bin/sh -ex

package=$1

if [ "$package" = "" ]; then
  echo "Missing package name parameter"
  exit 1
fi

# source common variables
. "$(dirname "$0")/common"

if [ ! -d "$PACKAGES_DIR/$package" ]; then
  echo "Package '$package' does not exist"
  exit 2
fi

version=$(exec "$SCRIPTS_DIR/version" "$package")

echo "==> Building $package version $version"

mkdir -p "$BUILD_DIR"

DEBUILD_DIR="$BUILD_DIR/$package-$version"

cp -r "$PACKAGES_DIR/$package" "$DEBUILD_DIR"

PREV_PWD=$(pwd)
cd "$DEBUILD_DIR"

mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"

debuild -i -us -uc -b

cd "$PREV_PWD"
