#!/bin/sh -e

# source common variables
. $(dirname "$0")/common

# get all git submodules
PREV_PWD=$(pwd)
cd "$PACKAGES_DIR"
git submodule update --init --recursive
cd "$PREV_PWD"

# build all packages
packages=$(ls "$PACKAGES_DIR")
for package in $packages; do
  exec "$SCRIPTS_DIR/build" "$package"
done
