name: Update Debian repository

on:
  push:
    branches:
      - main
  pull_request:

env:
  REPO_URL: "https://deb.teapot.ovh"

jobs:
  build:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: "debian:bookworm"
    environment:
      name: build
    steps:
      - name: Install git
        run: |
          apt update
          apt install -y git

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt install -y devscripts build-essential lintian reprepro

      - name: Compile all packages
        run: |
          git config --global --add safe.directory $(pwd)
          ./scripts/buildall

      # https://stackoverflow.com/a/61748039
      - name: Setup the GPG key
        run: |
          echo -n "$GPG_KEY" | gpg --armor --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Get the previous repository
        run: |
          wget "$REPO_URL/backup.tar.gz"
          tar xfz backup.tar.gz

      - name: Generate reprepro repository
        run: |
          ./scripts/reprepro

      - name: Store repositories/ as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: repositories
          path: repositories

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repositories
          path: repositories

      - name: Tar the repositories/ folder
        run: tar czf backup.tar.gz repositories/

      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install statik
        run: go install github.com/lucat1/statik@latest

      - name: Generate static directory listing
        run: >
            $(go env GOPATH)/bin/statik
            -l
            -b "$REPO_URL"
            -e "conf|db"
            repositories
            website

      - name: Move the backup to the website folder
        run: mv backup.tar.gz website

      - name: Store website as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: website
          path: website

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: website
